services:
  - type: web
    name: cobalt-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
