services:
  - type: web
    name: cobalt-api
    env: node
    plan: free
    rootDir: api
    buildCommand: npm install
    startCommand: node src/cobalt.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
